language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t maxim2andreev/docker-react-course .
    
script:
    - docker run -e CI=true maxim2andreev/docker-react-course npm run test