language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t maxim2andreev/docker-react-course .
    
script:
    - docker run -e CI=true maxim2andreev/docker-react-course npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker-react-course"
    env: "Dockerreactcourse-env"
    bucket_name: "elasticbeanstalk-eu-central-1-217003881490"
    bucket_path: "docker-react-course"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY